config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  delete 'log_out' => 'sessions#destroy'

  resources :messages

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  def sender
    @user ||= User.find_by(id: sender_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
 
  def received_messages
    Message.where(recipient_id: id)
  end

  def sent_messages
    Message.where(sender_id: id)
  end

  def unread_messages
    received_messages.where(is_read: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user, except: [:new]


  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if session.has_key?(:user_id)
      # do nothing
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  skip_before_action :authenticate_user, only: [:new]

  def index
    @messages = current_user.received_messages
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        flash[:success] = "Welcome! Signed in."
        session[:user_id] = @user.id
        redirect_to message_path
      else
        flash.now[:error] = "Wrong password!"
        render 'new'
      end
    else
      flash.now[:error] = "User not found."
      redirect_to action: 'new', show_hint: true
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {success: "Logged Out"}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.name}"
      redirect_to root_path
    else
      flash[:error] = "Password did not match!"
      render 'new'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # file: application_helper.rb
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome!</h1>

<% if current_user.present? %>
  Welcome <%= current_user.name %> to SimpleChat!
<% else %>
  <%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
  <%= link_to "Sign In", new_session_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">SimpleChat</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to "Sign Out", log_out_path, method: 'delete', class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <%= flash_messages %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<table class="table table-stripped">
  <thead class="thead thead-default"> 
    <tr>
      <th>Sender</th>
      <th>Subject</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender.name %></td>
        <td><%= message.subject %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <%= f.submit "Sign Up", class: 'btn btn-primary' %>
<% end %>